spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/feira
    username: app_feira
    password: app_feira
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  application:
    name: feira

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}