CREATE TABLE tb_endereco(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cep VARCHAR(10) NOT NULL,
    bairro VARCHAR(40) NOT NULL,
    cidade VARCHAR(60) NOT NULL,
    complemento VARCHAR(250) NOT NULL,
    funcionario_id INT NOT NULL,
    creation_date TIMESTAMP WITH TIME ZONE NOT NULL,
    update_date TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_endereco_pessoa FOREIGN KEY(funcionario_id) REFERENCES tb_pessoa(id)
);