CREATE TABLE tb_compra(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_comprador VARCHAR(60) NOT NULL,
    numero_comprador DECIMAL(3,2) NOT NULL,
    tipo_entrega VARCHAR(50) NOT NULL,
    valor_total DECIMAL(10,2) NOT NULL,
    forma_pagamento VARCHAR(40) NOT NULL,
    mensagem VARCHAR(100) NOT NULL,
    status VARCHAR(15) NOT NULL,
    creation_date TIMESTAMP WITH TIME ZONE NOT NULL
);